/** Paths that exist. A link to anything else is not rendered. */
export const OBJAVLJENO = new Set([
  "/simptomi/",
  "/simptomi/dijete-hrce/",
  "/simptomi/disanje-na-usta/",
  "/simptomi/stanke-u-disanju/",
  "/simptomi/umor-i-los-san/",
  "/simptomi/bol-u-uhu/",
  "/simptomi/iscjedak-iz-uha/",
  "/simptomi/slabiji-sluh/",
  "/simptomi/kasni-govor/",
  "/simptomi/ceste-angine/",
  "/simptomi/govor-kroz-nos/",
  "/simptomi/krvarenje-iz-nosa/",
  "/simptomi/iscjedak-iz-jedne-nosnice/",
  "/simptomi/strano-tijelo/",
  "/simptomi/kvrgice-na-vratu/",
  "/simptomi/dugotrajna-hunjavica/",
  "/simptomi/promuklost/",
  "/simptomi/sumno-disanje-dojence/",
  "/simptomi/klempave-usi/",
  "/stanja/",
  "/stanja/treci-krajnik/",
  "/stanja/krajnici-kod-djece/",
  "/stanja/apneja-u-snu/",
  "/stanja/upala-srednjeg-uha/",
  "/stanja/ponavljajuce-upale-uha/",
  "/stanja/tekucina-iza-bubnjica/",
  "/stanja/eustahijeva-cijev/",
  "/stanja/upala-zvukovoda/",
  "/stanja/usni-cep/",
  "/stanja/angina-i-tonzilitis/",
  "/stanja/pfapa-sindrom/",
  "/stanja/alergijski-rinitis/",
  "/stanja/sinusitis-kod-djece/",
  "/stanja/kratka-podjezicna-resica/",
  "/stanja/cvorici-na-glasnicama/",
  "/stanja/laringomalacija/",
  "/stanja/preaurikularna-fistula/",
  "/zahvati/",
  "/zahvati/adenoidektomija/",
  "/zahvati/ventilacijske-cjevcice/",
  "/pregled-i-endoskopija/",
  "/provjera-simptoma/",
]);

export const NAZIVI: Record<string, string> = {
  "/simptomi/": "Simptomi",
  "/simptomi/dijete-hrce/": "Dijete hrče",
  "/simptomi/disanje-na-usta/": "Dijete diše na usta",
  "/simptomi/stanke-u-disanju/": "Stanke u disanju",
  "/simptomi/umor-i-los-san/": "Umor i loš san",
  "/simptomi/bol-u-uhu/": "Bol u uhu",
  "/simptomi/iscjedak-iz-uha/": "Iscjedak iz uha",
  "/simptomi/slabiji-sluh/": "Slabiji sluh",
  "/simptomi/kasni-govor/": "Kasni govor",
  "/simptomi/ceste-angine/": "Česte angine",
  "/simptomi/govor-kroz-nos/": "Govor kroz nos",
  "/simptomi/krvarenje-iz-nosa/": "Krvarenje iz nosa",
  "/simptomi/iscjedak-iz-jedne-nosnice/": "Iscjedak iz jedne nosnice",
  "/simptomi/strano-tijelo/": "Strano tijelo",
  "/simptomi/kvrgice-na-vratu/": "Kvrgice na vratu",
  "/simptomi/dugotrajna-hunjavica/": "Dugotrajna hunjavica",
  "/simptomi/promuklost/": "Promuklost",
  "/simptomi/sumno-disanje-dojence/": "Šumno disanje",
  "/simptomi/klempave-usi/": "Klempave uši",
  "/stanja/": "Stanja",
  "/stanja/treci-krajnik/": "Treći krajnik",
  "/stanja/krajnici-kod-djece/": "Krajnici",
  "/stanja/apneja-u-snu/": "Apneja u snu",
  "/stanja/upala-srednjeg-uha/": "Upala srednjeg uha",
  "/stanja/ponavljajuce-upale-uha/": "Ponavljajuće upale uha",
  "/stanja/tekucina-iza-bubnjica/": "Tekućina iza bubnjića",
  "/stanja/eustahijeva-cijev/": "Eustahijeva cijev",
  "/stanja/upala-zvukovoda/": "Upala zvukovoda",
  "/stanja/usni-cep/": "Ušni čep",
  "/stanja/angina-i-tonzilitis/": "Angina",
  "/stanja/pfapa-sindrom/": "PFAPA",
  "/stanja/alergijski-rinitis/": "Alergijski rinitis",
  "/stanja/sinusitis-kod-djece/": "Sinusitis",
  "/stanja/kratka-podjezicna-resica/": "Podjezična resica",
  "/stanja/cvorici-na-glasnicama/": "Čvorići na glasnicama",
  "/stanja/laringomalacija/": "Laringomalacija",
  "/stanja/preaurikularna-fistula/": "Rupica ispred uha",
  "/zahvati/": "Zahvati",
  "/zahvati/adenoidektomija/": "Operacija trećeg krajnika",
  "/zahvati/ventilacijske-cjevcice/": "Ventilacijske cjevčice",
  "/pregled-i-endoskopija/": "Pregled i endoskopija",
  "/provjera-simptoma/": "Provjera simptoma",
};
